version: '3.8'

services:
  pdf-extractor:
    build: .
    container_name: pdf-outline-extractor
    volumes:
      - ./input:/app/input:ro
      - ./output:/app/output
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=INFO
      - MAX_PROCESSING_TIME=10
      - BATCH_SIZE=5
    restart: unless-stopped
    
  # Optional: Web interface for monitoring
  web-interface:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: pdf-extractor-web
    ports:
      - "8080:8080"
    volumes:
      - ./output:/app/output:ro
    depends_on:
      - pdf-extractor
    profiles:
      - web

volumes:
  logs:
    driver: local